---
gitlab_config_dir: "/opt/gitlab/server/config"
gitlab_container_name: "gitlab"
gitlab_container_backup_path: "/var/opt/gitlab/backups"
vault_smb_secret_path: "kv/data/devops/server/smb/someserver01"
vault_extra_options: ""
vault_options: " url={{ vault_url }} auth_method=approle role_id={{ vault_role_id }} secret_id={{ vault_secret_id }} {{ vault_extra_options }}"
network_share_path: "//someserver01.oa.internal/somepath$/devops_backup"
max_backups: 3