---
- name: "Run OS check"
  ansible.builtin.include_role:
    name: devops.utils.assert_run_in_os
  vars:
    required_os_families:
    - "Debian"
- name: "Ensure all machines have basic apt packages installed"
  ansible.builtin.include_role:
    name: devops.utils.try_apt_install
  vars:
    try_apt_packages:
    - apt-transport-https
    - ca-certificates
    - cifs-utils
    - curl
    - dnsutils
    - ethtool
    - git
    - git-lfs
    - gnupg
    - grep
    - gzip
    - iperf3
    - iproute2
    - iputils-ping
    - jq
    - ldap-utils
    - less
    - lsof
    - nano
    - netcat
    - nftables
    - openssh-client
    - openssl
    - privoxy
    - rsync
    - sed
    - socat
    - tcpdump
    - tmux
    - traceroute
    - tree
    - unzip
    - vim
    - wget
    - wrk
    - xclip
    - zip