---
- name: Ensure all machines have basic apt packages installed
  hosts: all
  become: true
  gather_facts: false
  environment: "{{ proxy_env if 'internal' in group_names else {} }}"
  roles:
  - gather_basic_facts
  - install_basic_os_packages