---
- name: Install Docker Engine via Ansible Galaxy Role
  hosts: all
  gather_facts: false
  become: true
  vars:
    docker_edition: 'ce'
    docker_users:
    - devops
  environment: "{{ proxy_env if 'internal' in group_names else {} }}"
  roles:
  - gather_basic_facts
  - geerlingguy.docker