---
- name: Install and configure Privoxy to forward socks5
  hosts: all
  become: true
  gather_facts: false
  environment: "{{ proxy_env if 'internal' in group_names else {} }}"
  roles:
  - gather_basic_facts
  - setup_privoxy_forward_socks5